#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

git stash --quiet --keep-index --message "lint-staged automatic backup"
npx lint-staged --shell --verbose --no-stash
git add .
git stash pop --quiet
