#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

zero=$(git hash-object --stdin < /dev/null | tr '[0-9a-f]' '0')

while read local_ref local_oid remote_ref remote_oid; do
  if test "$local_oid" = "$zero"; then
    # Handle delete
    :
  else
    if test "$remote_oid" = "$zero"; then
      # New branch, examine all commits
      range="origin/main"
    else
      # Update to existing branch, examine new commits
      range="$remote_oid"
    fi

    echo "$range...$local_oid"
    npx cross-env NO_FIX=1 npx lint-staged --shell --verbose --no-stash --diff "$range...$local_oid"
  fi
done

npm run build
