#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

zero=$(git hash-object --stdin < /dev/null | tr '[0-9a-f]' '0')

while read local_ref local_oid remote_ref remote_oid; do
  if test "$local_oid" = "$zero"; then
    # Handle delete
    :
  else
    if test "$remote_oid" = "$zero"; then
      # New branch, examine all commits
      range="origin/main"
    else
      # Update to existing branch, examine new commits
      range="$remote_oid"
    fi

    git stash

    echo "$range...$local_oid"
    npx lint-staged --shell --verbose --diff "$range...$local_oid"

    if ! git diff-index --quiet HEAD -- ; then
      git --no-pager diff --text HEAD
      git reset --hard
      git stash pop || true
      exit 1
    fi
    
    git stash pop || true
  fi
done

npm run build
